//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public commande()
        {
            this.bon_de_livraison = new HashSet<bon_de_livraison>();
            this.compose = new HashSet<compose>();
        }
    
        public int num_commande { get; set; }
        public Nullable<int> num_facture { get; set; }
        public Nullable<bool> paiement_a_la_commade { get; set; }
        public Nullable<decimal> prix_vente_ht { get; set; }
        public Nullable<double> remise_supp_commande { get; set; }
        public Nullable<System.DateTime> date_commande { get; set; }
        public Nullable<System.DateTime> date_reglem_commande { get; set; }
        public string statut_commande { get; set; }
        public Nullable<int> num_client { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bon_de_livraison> bon_de_livraison { get; set; }
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compose> compose { get; set; }
    }
}
