//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class fournisseur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fournisseur()
        {
            this.fourni = new HashSet<fourni>();
        }
    
        public string siret_fourni { get; set; }
        public string nom_long_arti_fourni { get; set; }
        public string adress_fourni { get; set; }
        public Nullable<int> code_post_fourni { get; set; }
        public string ville_fourni { get; set; }
        public string mail_fourni { get; set; }
        public string tel_fix_fourni { get; set; }
        public string tel_mob_fourni { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fourni> fourni { get; set; }
    }
}
