//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fil_rougeEntities : DbContext
    {
        public fil_rougeEntities()
            : base("name=fil_rougeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> article { get; set; }
        public virtual DbSet<bon_de_livraison> bon_de_livraison { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<commande> commande { get; set; }
        public virtual DbSet<compose> compose { get; set; }
        public virtual DbSet<fourni> fourni { get; set; }
        public virtual DbSet<fournisseur> fournisseur { get; set; }
        public virtual DbSet<possede> possede { get; set; }
        public virtual DbSet<rubrique> rubrique { get; set; }
        public virtual DbSet<service_commercial> service_commercial { get; set; }
    }
}
